config/routes.rb
Rails.application.routes.draw do
  resources :nuestro_equipos
  resources :homes
  resources :contacts
  resources :checkins
  resources :terminos
  devise_for :admins, path: 'admins'
  resources :arriendos
  resources :informacions
  devise_for :users, path: 'users'
  resources :equipos
  resources :users
  root to: 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arriendo.rb
class Arriendo < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :equipo

end

app/models/checkin.rb
class Checkin < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user, optional: true
  after_create :send_question

  def send_question
    ContactMailer.contactar(self).deliver
  end
end

app/models/equipo.rb
class Equipo < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/informacion.rb
class Informacion < ApplicationRecord
end

app/models/nuestro_equipo.rb
class NuestroEquipo < ApplicationRecord
end

app/models/termino.rb
class Termino < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :contactos
  has_many :arriendos
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:email, :message, :user_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:snowforecast, :camino)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arriendos_helper.rb
module ArriendosHelper

  def send_email(arr_final)
  #  if arr_final.endof
      if arr_final.user_id
        ArriendoMailer.order_confirm(User.find(arr_final.user_id), Equipo.find(arr_final.equipo_id), arr_final).deliver
        ArriendoMailer.order_alert(User.find(arr_final.user_id), Equipo.find(arr_final.equipo_id), arr_final).deliver
      else
        ArriendoMailer.order_confirm(arr_final, Equipo.find(arr_final.equipo_id), arr_final).deliver
        ArriendoMailer.order_alert(arr_final, Equipo.find(arr_final.equipo_id), arr_final).deliver
      end
  #  end
  end

end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/informacion_helper.rb
module InformacionHelper
end

app/helpers/informacions_helper.rb
module InformacionsHelper
end

app/helpers/terminos_helper.rb
module TerminosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if user_signed_in? %>

    <div class="field">
      <p><%= f.label "Email" %></p>
      <%= f.text_field :email, :value => current_user.email %>
    </div>
    <div class="field">
      <p><%= f.label "Escríbenos!" %></p>
      <%= f.text_area :message %>
    </div>

    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>

    <div class="actions" style="padding-top:10px; padding-bottom:10px;">
      <%= f.submit %>
    </div>
  <% else %>

    <div class="field">
      <p><%= f.label "Email" %></p>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <p><%= f.label "Escríbenos!" %></p>
      <%= f.text_area :message %>
    </div>

    <div class="actions" style="padding-top:10px; padding-bottom:10px;">
      <%= f.submit 'Enviar'%>
    </div>
  <% end %>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= contact.user_id %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<br>
</br>
<br>
</br>
<div class="container">

  <h1>Contacto</h1>

<br></br>

  <%= render 'form', contact: @contact %>

  <%= link_to 'Atrás', arriendos_path %>

<br>
</br>

  <%="Telefono - (2) 2215 6089"%>

</div>

<br>
</br>
<br>
</br>

app/views/contacts/show.html.erb
<br>
</br>
<br>
</br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @contact.user_id %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>