config/routes.rb
Rails.application.routes.draw do
  resources :nuestro_equipos
  resources :homes
  resources :contacts
  resources :checkins
  resources :terminos
  devise_for :admins, path: 'admins'
  resources :arriendos
  resources :informacions
  devise_for :users, path: 'users'
  resources :equipos
  resources :users
  root to: 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arriendo.rb
class Arriendo < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :equipo

end

app/models/checkin.rb
class Checkin < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user, optional: true
  after_create :send_question

  def send_question
    ContactMailer.contactar(self).deliver
  end
end

app/models/equipo.rb
class Equipo < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/informacion.rb
class Informacion < ApplicationRecord
end

app/models/nuestro_equipo.rb
class NuestroEquipo < ApplicationRecord
end

app/models/termino.rb
class Termino < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :contactos
  has_many :arriendos
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:snowforecast, :camino)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if params[:id] = "sign_out"
        sign_out current_user
      else
        @user = User.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nombre, :apellidopaterno, :apellidomaterno, :document, :nac, :peso, :altura, :talla, :talla_parka, :talla_pantalon, :experience)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arriendos_helper.rb
module ArriendosHelper

  def send_email(arr_final)
  #  if arr_final.endof
      if arr_final.user_id
        ArriendoMailer.order_confirm(User.find(arr_final.user_id), Equipo.find(arr_final.equipo_id), arr_final).deliver
        ArriendoMailer.order_alert(User.find(arr_final.user_id), Equipo.find(arr_final.equipo_id), arr_final).deliver
      else
        ArriendoMailer.order_confirm(arr_final, Equipo.find(arr_final.equipo_id), arr_final).deliver
        ArriendoMailer.order_alert(arr_final, Equipo.find(arr_final.equipo_id), arr_final).deliver
      end
  #  end
  end

end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/informacion_helper.rb
module InformacionHelper
end

app/helpers/informacions_helper.rb
module InformacionsHelper
end

app/helpers/terminos_helper.rb
module TerminosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/_form.html.erb
<%= form_for(home) do |f| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Snowforecast" %>
    <%= f.text_field :snowforecast %>
  </div>

  <div class="field">
    <%= f.label "Condiciones del camino" %>
    <%= f.text_area :camino %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
  <header class="viewport" style="overflow: hidden; min-width: 100%">
       <img src="/images/IMG_4601.jpg" alt="Homepage image" class="responsive">
  </header>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<div class="container">
  <br>
  </br>
  <body class="home-bg">
    <div style="margin-top:-750px;">
      <br>
      </br>
      <h1 style="font-size:60px">Bienvenido a Rental Ski!</h1>
      <br>
      </br>
      <br>
      </br>
      <table>
        <div style="text-align: center;">
          <td style="padding-right: 100px;">
            <%= link_to 'Check In', arriendos_path, :class => "btn btn-primary btn-hg" %>
          </td>

          <td style="padding-right: 100px;">
            <%= link_to 'Precios y packs', equipos_path, :class => "btn btn-primary btn-hg" %>
          </td>

          <td style="padding-right: 100px;">
            <%= link_to 'Nuestro equipo', nuestro_equipos_path, :class => "btn btn-primary btn-hg" %>
          </td>
        </div>
      </table>
      <br>
      </br>
      <br>
      </br>
    </div>
    <br>
    </br>
    <br>
    </br>
    <br>
    </br>


    </body>
</div>
<div style="padding-bottom:6.5px;">
    <table class="table" style="border: 3px solid black;">
      <tbody class= "jumbotron jumbotron-fluid" style="background-color: #dddddd;border: 1px solid black;">
        <% @homes.each do |home| %>
            <tr style="border: 3px solid black;">
              <td class = "container" style="max-width:200px;border: 3px solid black;" ><%= "Snowforecast" %></td>
              <td class = "container" style="background-color: #428bca;border: 1px solid black"><%= home.snowforecast %></td>
                <% if user_signed_in? %>
                  <% if current_user.admin %>
                    <td>
                      <%= link_to 'Editar', edit_home_path(home) %>
                    </td>
                  <% end %>
                <% end %>
            </tr>
          <tr style="border: 3px solid black;">
              <td class = "container" style="max-width: 200px;border: 3px solid black"><%= "Condiciones del camino" %></td>
              <td class = "container" style="background-color: #428bca;border: 3px solid black"><%= home.camino %></td>
                <% if user_signed_in? %>
                  <% if current_user.admin %>
                  <td>
                    <%= link_to 'Editar', edit_home_path(home) %>
                  </td>
                  <% end %>
                <% end %>
            </tr>
        <% end %>
        <% if @homes.count < 1 %>
          <% if user_signed_in? %>
            <% if current_user.admin %>
              <%= link_to 'Agregar Snowforecast', new_home_path %>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </table>
</div>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Atrás', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>