config/routes.rb
Rails.application.routes.draw do
  resources :nuestro_equipos
  resources :homes
  resources :contacts
  resources :checkins
  resources :terminos
  devise_for :admins, path: 'admins'
  resources :arriendos
  resources :informacions
  devise_for :users, path: 'users'
  resources :equipos
  resources :users
  root to: 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arriendo.rb
class Arriendo < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :equipo

end

app/models/checkin.rb
class Checkin < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user, optional: true
  after_create :send_question

  def send_question
    ContactMailer.contactar(self).deliver
  end
end

app/models/equipo.rb
class Equipo < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/informacion.rb
class Informacion < ApplicationRecord
end

app/models/nuestro_equipo.rb
class NuestroEquipo < ApplicationRecord
end

app/models/termino.rb
class Termino < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :contactos
  has_many :arriendos
end

app/controllers/equipos_controller.rb
class EquiposController < ApplicationController
  before_action :set_equipo, only: [:show, :edit, :update, :destroy]

  # GET /equipos
  # GET /equipos.json
  def index
    @equipos = Equipo.all
  end

  # GET /equipos/1
  # GET /equipos/1.json
  def show
  end

  # GET /equipos/new
  def new
    @equipo = Equipo.new
  end

  # GET /equipos/1/edit
  def edit
  end

  # POST /equipos
  # POST /equipos.json
  def create
    @equipo = Equipo.new(equipo_params)

    respond_to do |format|
      if @equipo.save
        format.html { redirect_to @equipo, notice: 'Equipo was successfully created.' }
        format.json { render :show, status: :created, location: @equipo }
      else
        format.html { render :new }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipos/1
  # PATCH/PUT /equipos/1.json
  def update
    respond_to do |format|
      if @equipo.update(equipo_params)
        format.html { redirect_to @equipo, notice: 'Equipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipo }
      else
        format.html { render :edit }
        format.json { render json: @equipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipos/1
  # DELETE /equipos/1.json
  def destroy
    @equipo.destroy
    respond_to do |format|
      format.html { redirect_to equipos_url, notice: 'Equipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipo
      @equipo = Equipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipo_params
      params.require(:equipo).permit(:name, :description, :picture, :price)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:snowforecast, :camino)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arriendos_helper.rb
module ArriendosHelper

  def send_email(arr_final)
  #  if arr_final.endof
      if arr_final.user_id
        ArriendoMailer.order_confirm(User.find(arr_final.user_id), Equipo.find(arr_final.equipo_id), arr_final).deliver
        ArriendoMailer.order_alert(User.find(arr_final.user_id), Equipo.find(arr_final.equipo_id), arr_final).deliver
      else
        ArriendoMailer.order_confirm(arr_final, Equipo.find(arr_final.equipo_id), arr_final).deliver
        ArriendoMailer.order_alert(arr_final, Equipo.find(arr_final.equipo_id), arr_final).deliver
      end
  #  end
  end

end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/informacion_helper.rb
module InformacionHelper
end

app/helpers/informacions_helper.rb
module InformacionsHelper
end

app/helpers/terminos_helper.rb
module TerminosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/equipos/_form.html.erb
<%= form_for(equipo) do |f| %>
  <% if equipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipo.errors.count, "error") %> No se pudo guardar este equipo:</h2>

      <ul>
      <% equipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Equipo' %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label 'Descripción' %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label 'Foto' %>
    <%= f.text_field :picture %>
  </div>

  <div class="field">
    <%= f.label 'Precio' %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label 'Stock' %>
    <%= f.number_field :stock %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/equipos/edit.html.erb
<h1>Editing Equipo</h1>

<%= render 'form', equipo: @equipo %>

<%= link_to 'Show', @equipo %> |
<%= link_to 'Back', equipos_path %>

app/views/equipos/index.html.erb
<br>
</br>

<div class="container">
  <h1>Equipos</h1>
  <br>
  </br>
  <div class="table-responsive">
    <table class="table table-striped">
      <!-- <thead>
        <tr>
          <th>Equipo</th>
          <th>Detalles</th>
          <th>Precio</th>
          <th>Foto</th>
          <th>Stock</th>
          <th colspan="3"></th>
        </tr>
      </thead> -->

      <tbody>
        <% sizes = ["240x120", "240x120", "240x120", "240x120", "240x60", "240x60", "60x60" , "60x60" , "60x60" , "60x60" , "60x60" , "60x60" , "60x60" , "60x60" , "60x60" , "60x60"] %>
        <% counter = 0 %>
        <% @equipos.order('price DESC').each do |equipo| %>
          <tr>
            <td style="padding-right: 0px">
            <h3><strong><%= equipo.name %></strong></h3>
            <header class="viewport" style="padding-top: 8px">
                <%=  image_tag(equipo.picture, size:sizes[counter]) %>
            </header>
            </td>
            <td>
            <strong> Descripción </strong>
            <div style="white-space:pre-wrap; padding-top: 8px"><%= equipo.description %></div>
            </td>
            <td style="vertical-align: middle">
            <strong> Precio web </strong>
            <div style="padding-top: 8px"><%= "$ " + equipo.price.to_s %></div>
            </td>
            <!-- <td><%= equipo.stock %></td> -->
            <% if params[:nroarr].present? %>
              <td style="vertical-align: middle"><%= link_to 'Reservar', new_arriendo_path(:eq => equipo.id, :arr => Arriendo.find(params[:nroarr]).id), :class=>"btn btn-primary btn-2"  %></td>
            <% else %>
              <td style="vertical-align: middle"><%= link_to 'Reservar', new_arriendo_path(:eq => equipo.id), :class=>"btn btn-primary btn-2"  %></td>
            <% end %>
            <% if user_signed_in? %>
              <% if current_user.admin %>
                  <td><%= link_to 'Editar', edit_equipo_path(equipo) %></td>
                  <td><%= link_to 'Eliminar', equipo, method: :delete, data: { confirm: 'Seguro?' } %></td>
                <% end %>
            <% end %>
          </tr>
          <% counter += 1 %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>
<% if user_signed_in? %>
  <% if current_user.admin %>
    <%= link_to 'Nuevo Equipo', new_equipo_path %>
  <% end %>
<% end %>

app/views/equipos/new.html.erb
<br>
</br>

<div class="container">

  <h1>Nuevo Equipo</h1>

  <%= render 'form', equipo: @equipo %>

  <%= link_to 'Atrás', equipos_path %>

<div>

app/views/equipos/show.html.erb
<br>
</br>

<div class="container">
  <div class = "jumbotron" style="background-color: #ffcc66">
    <p>
      <strong>Equipo:</strong>
      <%= @equipo.name %>
    </p>

    <p>
      <strong>Detalles:</strong>
      <%= @equipo.description %>
    </p>

    <p>
      <strong>Precio:</strong>
      <%= @equipo.price %>
    </p>
    <p>
      <strong>Foto:</strong>
      <%= @equipo.picture %>
    </p>
    <% if params[:na].present? %>
      <p>
      <%= link_to 'Arrendar', new_arriendo_path(:eq => @equipo.id, :arr => Arriendo.find(params[:na]).id) %>
      </p>
    <% else %>
      <p>
        <%= link_to 'Arrendar', new_arriendo_path(:eq => @equipo.id) %>
      </p>
    <% end %>
  </div>

  <%= link_to 'Editar', edit_equipo_path(@equipo) %> |
  <%= link_to 'Volver', equipos_path %>
</div>