config/routes.rb
Rails.application.routes.draw do
  resources :nuestro_equipos
  resources :homes
  resources :contacts
  resources :checkins
  resources :terminos
  devise_for :admins, path: 'admins'
  resources :arriendos
  resources :informacions
  devise_for :users, path: 'users'
  resources :equipos
  resources :users
  root to: 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arriendo.rb
class Arriendo < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :equipo

end

app/models/checkin.rb
class Checkin < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user, optional: true
  after_create :send_question

  def send_question
    ContactMailer.contactar(self).deliver
  end
end

app/models/equipo.rb
class Equipo < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/informacion.rb
class Informacion < ApplicationRecord
end

app/models/nuestro_equipo.rb
class NuestroEquipo < ApplicationRecord
end

app/models/termino.rb
class Termino < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :contactos
  has_many :arriendos
end

app/controllers/arriendos_controller.rb
class ArriendosController < ApplicationController
  before_action :set_arriendo, only: [:show, :edit, :update, :destroy]

  # GET /arriendos
  # GET /arriendos.json
  def index
    @arriendos = Arriendo.all
  end

  # GET /arriendos/1
  # GET /arriendos/1.json
  def show
  end

  # GET /arriendos/new
  def new
    @arriendo = Arriendo.new
  end

  # GET /arriendos/1/edit
  def edit

  end

  def link(nror)
    @arriendo = Arriendo.find(params[nror])
    @arriendo.user_id = current_user.id
  end

  # POST /arriendos
  # POST /arriendos.json
  def create
    @arriendo = Arriendo.new(arriendo_params)

    respond_to do |format|
      if @arriendo.save
        format.html { redirect_to @arriendo, notice: 'Arriendo was successfully created.' }
        format.json { render :show, status: :created, location: @arriendo }
      else
        format.html { render :new }
        format.json { render json: @arriendo.errors, status: :unprocessable_entity }
      end
    end

    (1..(@arriendo.cantidad-1)).each do |arriendo2|
      arriendo2 = Arriendo.new
      arriendo2.talla = @arriendo.talla
      arriendo2.talla_parka = @arriendo.talla_parka
      arriendo2.talla_pantalon = @arriendo.talla_pantalon
      arriendo2.altura = @arriendo.altura
      arriendo2.fecha = @arriendo.fecha
      arriendo2.peso = @arriendo.peso
      arriendo2.nombre = @arriendo.nombre
      arriendo2.apellidop = @arriendo.apellidop
      arriendo2.apellidom = @arriendo.apellidom
      arriendo2.nropedido = @arriendo.nropedido
      arriendo2.cantidad = @arriendo.cantidad
      arriendo2.user_id = @arriendo.user_id
      arriendo2.equipo_id = @arriendo.equipo_id
      arriendo2.email = @arriendo.email
      arriendo2.dias = @arriendo.dias
      arriendo2.experience = @arriendo.experience
      arriendo2.document = @arriendo.document
      arriendo2.save
    end

  end

  # PATCH/PUT /arriendos/1
  # PATCH/PUT /arriendos/1.json
  def update
    respond_to do |format|
      if @arriendo.update(arriendo_params)
        format.html { redirect_to @arriendo, notice: 'Arriendo was successfully updated.' }
        format.json { render :show, status: :ok, location: @arriendo }
      else
        format.html { render :edit }
        format.json { render json: @arriendo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arriendos/1
  # DELETE /arriendos/1.json
  def destroy
    Arriendo.where(nropedido: @arriendo.nropedido).each do |eliminado|
      eliminado.destroy
    end
    respond_to do |format|
      format.html { redirect_to arriendos_url, notice: 'Arriendo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arriendo
      @arriendo = Arriendo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arriendo_params
      params.require(:arriendo).permit(:talla, :talla_parka, :talla_pantalon, :document, :altura, :nac, :peso, :nombre, :apellidop, :apellidom, :nropedido, :cantidad, :user_id, :equipo_id, :email, :fecha, :dias, :experience)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:snowforecast, :camino)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arriendos_helper.rb
module ArriendosHelper

  def send_email(arr_final)
  #  if arr_final.endof
      if arr_final.user_id
        ArriendoMailer.order_confirm(User.find(arr_final.user_id), Equipo.find(arr_final.equipo_id), arr_final).deliver
        ArriendoMailer.order_alert(User.find(arr_final.user_id), Equipo.find(arr_final.equipo_id), arr_final).deliver
      else
        ArriendoMailer.order_confirm(arr_final, Equipo.find(arr_final.equipo_id), arr_final).deliver
        ArriendoMailer.order_alert(arr_final, Equipo.find(arr_final.equipo_id), arr_final).deliver
      end
  #  end
  end

end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/equipos_helper.rb
module EquiposHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/informacion_helper.rb
module InformacionHelper
end

app/helpers/informacions_helper.rb
module InformacionsHelper
end

app/helpers/terminos_helper.rb
module TerminosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/arriendos/_form.html.erb
<%= form_for(arriendo) do |f| %>
  <% if arriendo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arriendo.errors.count, "error") %> prohibited this arriendo from being saved:</h2>

      <ul>
      <% arriendo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if user_signed_in? %>

  <div class="field" style="padding-top:8px">
    <%= f.label 'Documento de identidad' %>
    <%= f.text_field :document, :value => current_user.document %>
  </div>

    <div class="field" style="padding-top:8px">
      <%= f.label 'Cantidad' %>
      <%= f.number_field :cantidad, :value => 1 %>
    </div>

    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>

    <div class="field">
      <%= f.hidden_field :equipo_id, :value => id %>
    </div>

    <% if params[:arr].present? %>
      <div class="field">
        <%= f.hidden_field :nropedido, :value => Arriendo.find(params[:arr]).nropedido %>
      </div>

      <div class="field" style="padding-top:8px">
        <%= f.hidden_field :fecha, :value => Arriendo.find(params[:arr]).fecha %>
      </div>

      <div class="field" style="padding-top:8px">
        <%= f.hidden_field :dias, :value => Arriendo.find(params[:arr]).dias %>
      </div>

    <% else %>
      <div class="field" style="padding-top:8px">
        <%= f.label "Fecha de Uso" %>
        <%= f.date_select :fecha, {order: [:day, :month, :year], prompt: {day: 'Dia', month: 'Mes', year: 'Año'}, start_year: Date.today.year, end_year: Date.today.year + 5}, :required => true %>
      </div>

      <div class="field">
        <%= f.hidden_field :nropedido, :value => Time.current.to_i.to_s + Equipo.find(id).name[0..2].upcase + id.to_s%>
      </div>

      <div class="field" style="padding-top:8px">
        <%= f.label "Días de Uso" %>
        <%= f.number_field :dias %>
      </div>

    <% end %>

    <div class="actions" style="padding-top:10px">
      <%= f.submit 'Reservar' %>
    </div>
  <% else %>

  <p>
    Si te registras, guardamos tus datos y no tienes que rellenarlos siempre!
  </p>

  <br>
  </br>

    <div class="field" style="padding-top:8px">
      <%= f.label :email %>
      <%= f.email_field :email, :required => true %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label 'Documento de identidad' %>
      <%= f.text_field :document %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label :nombre %>
      <%= f.text_field :nombre %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label 'Apellido Paterno' %>
      <%= f.text_field :apellidop %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label 'Apellido Materno' %>
      <%= f.text_field :apellidom %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.hidden_field :cantidad, :value => 1 %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label "Fecha de Uso" %>
      <%= f.date_select :fecha, {order: [:day, :month, :year], prompt: {day: 'Dia', month: 'Mes', year: 'Año'}, start_year: Date.today.year, end_year: Date.today.year + 5}, :required => true %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label "Días de Uso"%>
      <%= f.number_field :dias, :min => 1 %>
    </div>

    <div class="field">
      <%= f.hidden_field :equipo_id, :value => id %>
    </div>

    <div class="field">
      <%= f.hidden_field :nropedido, :value => Time.current.to_i.to_s + Equipo.find(id).name[0..2].upcase + id.to_s %>
    </div>

    <div class="actions" style="padding-top:8px">
      <%= f.submit 'Reservar' %>
    </div>
  <% end %>
<% end %>

app/views/arriendos/_form0.html.erb
<%= form_for(arriendo) do |f| %>
  <% if arriendo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arriendo.errors.count, "error") %> Error guardando el arriendo:</h2>

      <ul>
      <% arriendo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if user_signed_in? %>
    <div class="field" style="padding-top:8px">
      <%= f.label "Fecha de Uso" %>
      <%= f.date_select :fecha, {order: [:day, :month, :year], prompt: {day: 'Dia', month: 'Mes', year: 'Año'}, start_year: Date.today.year, end_year: Date.today.year + 5}, :value => arriendo.fecha %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label "Dias de Uso" %>
      <%= f.number_field :dias, :value => arriendo.dias %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label "Nivel" %>
      <%= f.number_field :experience, :min => 1, :max => 3, :value => arriendo.experience %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label 'Talla de bota' %>
      <%= f.number_field :talla, :value => arriendo.talla, :min => 1 %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label 'Talla de parka' %>
      <%= f.number_field :talla_parka, :value => arriendo.talla_parka, :min => 1 %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label 'Talla de pantalon' %>
      <%= f.number_field :talla_pantalo, :value => arriendo.talla_pantalon, :min => 1 %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label :altura %>
      <%= f.number_field :altura, :value => arriendo.altura, :min => 1 %>
    </div>

    <div class="field" style="padding-top:8px">
      <%= f.label :peso %>
      <%= f.number_field :peso, :value => arriendo.peso, :min => 1 %>
    </div>

    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>

    <div class="field">
      <%= f.hidden_field :equipo_id, :value => id %>
    </div>

    <% if params[:arr].present? %>
      <div class="field">
        <%= f.hidden_field :nropedido, :value => Arriendo.find(params[:arr]).nropedido %>
      </div>
    <% else %>
      <div class="field">
        <%= f.hidden_field :nropedido, :value => Time.current.to_i.to_s + Equipo.find(id).name[0..2].upcase + id.to_s%>
      </div>
    <% end %>

    <div class="actions" style="padding-top:10px">
      <%= f.submit %>
    </div>
  <% else %>

  <p>
    Registrate para hacer el check in!
  </p>

  <% end %>
<% end %>

app/views/arriendos/_form1.html.erb
<%= form_for(arriendo) do |f| %>
  <% if arriendo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arriendo.errors.count, "error") %> prohibited this arriendo from being saved:</h2>

      <ul>
      <% arriendo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label 'Codigo de reserva' %>
      <%= f.text_field :linker %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/arriendos/edit.html.erb
<br>
</br>
<div class="container">
  <h1>Editando Arriendo</h1>

  <%= render 'form0', arriendo: @arriendo %>

  <%= link_to 'Show', @arriendo %> |
  <%= link_to 'Atrás', arriendos_path %>
</div>

app/views/arriendos/index.html.erb
<br>
</br>

<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Reservas</h1>
  <div>
    <% if user_signed_in? %>
      <% if current_user.linker != nil %>
        <% agregar(current_user.id, current_user.linker) %>
      <% end %>
    <% end %>
  </div>
  <% if params[:arrid].present? %>
    <div> Arriendo listo, revise su email para confirmarlo! </div>
    <% send_email(Arriendo.find(params[:arrid])) %>
  <% end %>
  <% activo = false %>
  <%if activo%>
    <% if user_signed_in?%>
      <div class="container">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Código de arriendo</th>
                <th>Fecha</th>
                <th>Usuario</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @repeat = Array.new %>
              <% @arriendos.order('fecha').each do |arriendo| %>
                <% if DateTime.now < arriendo.fecha %>
                  <% if current_user.id == arriendo.user_id || current_user.admin %>
                    <% if @repeat.include?(arriendo.nropedido) == false %>
                      <tr>
                        <td><%= arriendo.nropedido %></td>
                        <td><%= arriendo.fecha.to_formatted_s(:long) %></td>
                        <td><%= arriendo.user_id %></td>
                        <td><%= link_to 'Ver Arriendo', arriendo_path(arriendo), :class=>"btn btn-primary btn-2" %></td>
                        <td><%= link_to 'Hacer Check In', edit_arriendo_path(arriendo), :class=>"btn btn-primary btn-2" %></td>
                        <td><%= link_to 'Eliminar Arriendo', checkin_path(:deleted => arriendo.nropedido), :class=>"btn btn-primary btn-4" %></td>
                        <!-- <td><%= link_to 'Eliminar Arriendo', arriendo_path(arriendo), :method => :delete, data: { confirm: 'Seguro?' }, :class=>"btn btn-primary btn-2" %></td> -->
                      </tr>
                      <% @repeat.push(arriendo.nropedido) %>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <br>
      </br>

      <div>
        <table>
          <td> <%= link_to 'Hacer otro arriendo', equipos_path, :class=>"btn btn-primary btn-4", :style=>"padding-right:10px" %> </td>

          <td> <%= link_to 'Unir arriendo a tu cuenta', edit_user_registration_path(:act => "link"), :class=>"btn btn-primary btn-5" %> </td>
        </table>
      </div>

    <% else %>
      <%= "Puedes realizar check-in previo si te registras! Tendrás todo listo al llegar" %>

    <% end %>
    <br>
    </br>
    <br>
    </br>
  </div>
<%else%>
  <%= "Pronto existirá la opción de check in para que disfrutes de tu equipo a la medida" %>
  <% if user_signed_in?%>
    <div class="container">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Código de arriendo</th>
              <th>Fecha</th>
              <th>Usuario</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @repeat = Array.new %>
            <% @arriendos.order('fecha').each do |arriendo| %>
              <% if DateTime.now < arriendo.fecha %>
                <% if current_user.id == arriendo.user_id || current_user.admin %>
                  <% if @repeat.include?(arriendo.nropedido) == false %>
                    <tr>
                      <td><%= arriendo.nropedido %></td>
                      <td><%= arriendo.fecha.to_formatted_s(:long) %></td>
                      <td><%= arriendo.user_id %></td>
                      <td><%= link_to 'Ver Arriendo', arriendo_path(arriendo), :class=>"btn btn-primary btn-3" %></td>
                      <td><%= link_to 'Hacer Check In', edit_arriendo_path(arriendo), :class=>"btn btn-primary btn-3" %></td>
                      <td><%= link_to 'Eliminar Arriendo', arriendo_path(arriendo, :deleted => "deleted"), :class=>"btn btn-primary btn-4" %></td>
                      <!-- <td><%= link_to 'Eliminar Arriendo', arriendo, :method => :delete, data: { confirm: 'Seguro?' }, :class=>"btn btn-primary btn-4" %></td> -->
                    </tr>
                    <% @repeat.push(arriendo.nropedido) %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <br>
    </br>
    <br>
    </br>
  <%end%>
<%end%>

app/views/arriendos/new.html.erb
<br>
</br>
<div class="container">
  <h1>Nuevo Arriendo</h1>
  <br>
  </br>
  <% if params[:arr].present? %>
    <%= render 'form', arriendo: @arriendo, id: Equipo.find(params[:eq]).id %>
  <% else %>
    <%= render 'form', arriendo: @arriendo, id: Equipo.find(params[:eq]).id %>
  <% end %>
</div>

<br>
</br>

app/views/arriendos/show.html.erb
<br>
</br>
<% if params[:deleted].present? %>
  <h1>Eliminados<h1>
  <%@nro = @arriendo.nropedido%>
  <% Arriendo.all.each do |arr| %>
    <% if arr.nropedido == @nro%>
      <tr>
        <div  class = "jumbotron" style="background-color: #ffcc66">
          <strong> <%= Equipo.find(arr.equipo_id).name %> </strong>
          <br>
          </br>
          <p>
            <%= "Fecha de uso: " + arr.fecha.to_s %>
          </p>
          <p>
            <%= "Nombre: " + arr.nombre + " " + arr.apellidop + " " + arr.apellidom %>
          </p>
          <p>
            <%= "Código de arriendo: " + arr.nropedido %>
          </p>
        </div>
        <% arr.destroy %>
      </tr>
    <%end%>
  <%end%>
<%else%>
  <div class="container">
    <p id="notice"><%= notice %></p>

    <% Arriendo.all.each do |arr| %>
      <% if arr.nropedido == @arriendo.nropedido %>
        <tr>
          <div  class = "jumbotron" style="background-color: #ffcc66">
            <strong> <%= Equipo.find(arr.equipo_id).name %> </strong>
            <br>
            </br>
            <p>
              <%= "Fecha de uso: " + arr.fecha.to_s %>
            </p>
            <p>
              <%= "Nombre: " + arr.nombre + " " + arr.apellidop + " " + arr.apellidom %>
            </p>
            <p>
              <%= "Código de arriendo: " + arr.nropedido %>
            </p>
          </div>
        </tr>
      <% end %>
    <% end %>
    <div>
      <table>
        <td> <%= link_to 'Continuar el pedido', equipos_path(:nroarr => @arriendo.id), :class=>"btn btn-primary btn-4" %> </td>
        <td><%= link_to 'Terminar pedido', arriendos_path(:arrid => @arriendo.id), :class=>"btn btn-primary btn-3" %></td>
    </table>
    </div>
<%end%>
</div>
<br>
</br>